using EasyRuoyi.Entities.Entities;
using EasyRuoyi.Entities.Enums;
using Furion;
using Furion.DatabaseAccessor;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace EasyRuoyi.Entities.SeedData
{
	public class MenuSeedData : IEntitySeedData<Menu>
	{
		public IEnumerable<Menu> HasData(DbContext dbContext, Type dbContextLocator)
		{
			Guid userId = Guid.Parse(App.Configuration["SeedData:UserInfo:Id"]);
			string name = App.Configuration["SeedData:UserInfo:Name"];
			DateTimeOffset time = DateTimeOffset.Parse("2023-1-1");
			return new[]
			{
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-4647-842f-702c52ca50c5"), Name = "系统管理", PId = null, FullPath = "系统管理/", EnumMenuType = EnumMenuType.Directory, PermissionCode = "", MenuIcon = "system", RouterName = "System", Path = "/system", Component = "", Sort = 1, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },

				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466c-8fa3-68324e69dbca"), Name = "用户管理", FullPath = "系统管理/用户管理/", PId = Guid.Parse("08daa9c2-cf08-4647-842f-702c52ca50c5"), EnumMenuType = EnumMenuType.Menu, PermissionCode = "system:user:list", MenuIcon = "user", RouterName = "User", Path = "/system/user", Component = "system/user/index", Sort = 1, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466d-8aa7-61d152a82a08"), Name = "用户查询", FullPath = "系统管理/用户管理/用户查询/", PId = Guid.Parse("08daa9c2-cf08-466c-8fa3-68324e69dbca"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:user:query", MenuIcon = "", Path = "", Component = "", Sort = 1, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466d-8c11-4841922dd430"), Name = "用户新增", FullPath = "系统管理/用户管理/用户新增/", PId = Guid.Parse("08daa9c2-cf08-466c-8fa3-68324e69dbca"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:user:add", MenuIcon = "", Path = "", Component = "", Sort = 2, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466d-8f69-e9af248a7e9a"), Name = "用户修改", FullPath = "系统管理/用户管理/用户修改/", PId = Guid.Parse("08daa9c2-cf08-466c-8fa3-68324e69dbca"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:user:edit", MenuIcon = "", Path = "", Component = "", Sort = 3, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466e-8246-642217ecf1fe"), Name = "用户删除", FullPath = "系统管理/用户管理/用户删除/", PId = Guid.Parse("08daa9c2-cf08-466c-8fa3-68324e69dbca"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:user:remove", MenuIcon = "", Path = "", Component = "", Sort = 4, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },

				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466e-8499-700ce0a16017"), Name = "角色管理", FullPath = "系统管理/角色管理/", PId = Guid.Parse("08daa9c2-cf08-4647-842f-702c52ca50c5"), EnumMenuType = EnumMenuType.Menu, PermissionCode = "system:role:list", MenuIcon = "peoples", RouterName = "Role", Path = "/system/role", Component = "system/role/index", Sort = 2, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466e-87b8-b44f3652ddc8"), Name = "角色查询", FullPath = "系统管理/角色管理/角色查询/", PId = Guid.Parse("08daa9c2-cf08-466e-8499-700ce0a16017"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:role:query", MenuIcon = "", Path = "", Component = "", Sort = 1, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466e-8957-bc339ab2fb1c"), Name = "角色新增", FullPath = "系统管理/角色管理/角色新增/", PId = Guid.Parse("08daa9c2-cf08-466e-8499-700ce0a16017"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:role:add", MenuIcon = "", Path = "", Component = "", Sort = 2, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466f-8af0-850d768cf158"), Name = "角色修改", FullPath = "系统管理/角色管理/角色修改/", PId = Guid.Parse("08daa9c2-cf08-466e-8499-700ce0a16017"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:role:edit", MenuIcon = "", Path = "", Component = "", Sort = 3, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466f-8c16-266c6e0fb639"), Name = "角色删除", FullPath = "系统管理/角色管理/角色删除/", PId = Guid.Parse("08daa9c2-cf08-466e-8499-700ce0a16017"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:role:remove", MenuIcon = "", Path = "", Component = "", Sort = 4, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },

				new Menu{ Id = Guid.Parse("08daa9c2-cf08-466f-8f97-cc651bdb79e5"), Name = "菜单管理", FullPath = "系统管理/菜单管理/", PId = Guid.Parse("08daa9c2-cf08-4647-842f-702c52ca50c5"), EnumMenuType = EnumMenuType.Menu, PermissionCode = "system:menu:list", MenuIcon = "tree-table", RouterName = "Menu", Path = "/system/menu", Component = "system/menu/index", Sort = 3, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-4670-8139-e1682f10bae7"), Name = "菜单查询", FullPath = "系统管理/菜单管理/菜单查询/", PId = Guid.Parse("08daa9c2-cf08-466f-8f97-cc651bdb79e5"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:menu:query", MenuIcon = "", Path = "", Component = "", Sort = 1, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-4670-8351-1628fbce7366"), Name = "菜单新增", FullPath = "系统管理/菜单管理/菜单新增/", PId = Guid.Parse("08daa9c2-cf08-466f-8f97-cc651bdb79e5"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:menu:add", MenuIcon = "", Path = "", Component = "", Sort = 2, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-4670-85aa-f81d31913533"), Name = "菜单修改", FullPath = "系统管理/菜单管理/菜单修改/", PId = Guid.Parse("08daa9c2-cf08-466f-8f97-cc651bdb79e5"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:menu:edit", MenuIcon = "", Path = "", Component = "", Sort = 3, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false },
				new Menu{ Id = Guid.Parse("08daa9c2-cf08-4670-8e03-f77d69f154a8"), Name = "菜单删除", FullPath = "系统管理/菜单管理/菜单删除/", PId = Guid.Parse("08daa9c2-cf08-466f-8f97-cc651bdb79e5"), EnumMenuType = EnumMenuType.Operation, PermissionCode = "system:menu:remove", MenuIcon = "", Path = "", Component = "", Sort = 4, IsCache = false, IsShow = true, IsEnable = true, CreatedUserId=userId, CreatedUserName=name, CreatedTime=time, UpdatedUserId=userId,UpdatedUserName=name,UpdatedTime=time, IsDeleted = false }
			};
		}
	}
}
